# Generated by Django 5.2.7 on 2025-10-25 04:05

from django.db import migrations, models
from django.utils.text import slugify

def set_unique_slugs(apps, schema_editor):
    # Get the Product model as it was at this point in time (important for migrations)
    Product = apps.get_model('products', 'Product') 

    # Iterate over all existing products
    for product in Product.objects.all():
        base_slug = slugify(product.name)
        slug = base_slug
        counter = 1

        # Ensure the slug is unique by checking against other products
        while Product.objects.exclude(pk=product.pk).filter(slug=slug).exists():
            slug = f"{base_slug}-{counter}"
            counter += 1

        product.slug = slug
        # Only save the 'slug' field, leaving created_at untouched
        product.save(update_fields=['slug'])

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        # 1. Add the nullable slug field (This was already in your file)
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),

        # 2. <<< THE CRITICAL ADDITION: Run the function to fill the slugs for existing data.
        migrations.RunPython(set_unique_slugs, migrations.RunPython.noop), 
        
        # 3. Alter the slug field to make it non-nullable (unique=True remains).
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        
        # 4. Your other AlterField operations can go here (or anywhere after step 1)
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=99),
        ),
    ]