# Generated by Django 5.2.7 on 2025-10-25 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_productimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferedItems',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
                ('offertype', models.TextField()),
            ],
            bases=('products.product',),
        ),
    ]
