# Generated by Django 5.2.7 on 2025-10-25 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_offereditems'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OfferedItems',
            new_name='OfferedItem',
        ),
    ]
