# Generated by Django 5.2.7 on 2025-10-25 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_rename_offereditems_offereditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_most_demanded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_selective',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='OfferedItem',
        ),
    ]
