# Generated by Django 5.2.7 on 2025-10-26 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_is_featured_product_is_most_demanded_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='image',
            new_name='image_url',
        ),
    ]
